version: '3'

services:

  database:
    container_name: mysql_customer_database
    image: mysql/mysql-server:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: customerdb
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
    
    ports:
      - "3320:3306"
    volumes:
      - .m2:/root/.m2
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - customer_network

  application:
    container_name: docker-customer-springboot
    restart: on-failure
    build:
      context: ./
      dockerfile: DockerFile
    ports:
      - "8091:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_customer_database:3306/employeedb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    depends_on:
      - database
    networks:
      - customer_network

networks:
 customer_network: